// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGoDbUserInfo = "go_db_user_info"

// GoDbUserInfo go_db_user_info
type GoDbUserInfo struct {
	UserID               int64      `gorm:"column:user_id;primaryKey;autoIncrement:true;comment:User ID" json:"user_id"`                                                                                   // User ID
	UserAccount          string     `gorm:"column:user_account;not null;comment:User account" json:"user_account"`                                                                                         // User account
	UserNickname         string     `gorm:"column:user_nickname;comment:User nickname" json:"user_nickname"`                                                                                               // User nickname
	UserAvatar           string     `gorm:"column:user_avatar;comment:User avatar" json:"user_avatar"`                                                                                                     // User avatar
	UserState            int32      `gorm:"column:user_state;not null;comment:User state: 0-Locked, 1-Activated, 2-Not Activated" json:"user_state"`                                                       // User state: 0-Locked, 1-Activated, 2-Not Activated
	UserMobile           string     `gorm:"column:user_mobile;comment:Mobile phone number" json:"user_mobile"`                                                                                             // Mobile phone number
	UserGender           int32      `gorm:"column:user_gender;comment:User gender: 0-Secret, 1-Male, 2-Female" json:"user_gender"`                                                                         // User gender: 0-Secret, 1-Male, 2-Female
	UserBirthday         *time.Time `gorm:"column:user_birthday;comment:User birthday" json:"user_birthday"`                                                                                               // User birthday
	UserEmail            string     `gorm:"column:user_email;comment:User email address" json:"user_email"`                                                                                                // User email address
	UserIsAuthentication int32      `gorm:"column:user_is_authentication;not null;comment:Authentication status: 0-Not Authenticated, 1-Pending, 2-Authenticated, 3-Failed" json:"user_is_authentication"` // Authentication status: 0-Not Authenticated, 1-Pending, 2-Authenticated, 3-Failed
	CreatedAt            time.Time  `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:Record creation time" json:"created_at"`                                                                    // Record creation time
	UpdatedAt            time.Time  `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:Record update time" json:"updated_at"`                                                                      // Record update time
}

// TableName GoDbUserInfo's table name
func (*GoDbUserInfo) TableName() string {
	return TableNameGoDbUserInfo
}
