// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGoDbVerifyOtp = "go_db_verify_otp"

// GoDbVerifyOtp account_user_verify
type GoDbVerifyOtp struct {
	VerifyID        int32     `gorm:"column:verify_id;primaryKey;autoIncrement:true;comment:Verification ID" json:"verify_id"`                  // Verification ID
	UserID          int64     `gorm:"column:user_id;not null;comment:User ID" json:"user_id"`                                                   // User ID
	VerifyOtp       string    `gorm:"column:verify_otp;not null;comment:One-time password (OTP)" json:"verify_otp"`                             // One-time password (OTP)
	VerifyKey       string    `gorm:"column:verify_key;not null;comment:Verification key" json:"verify_key"`                                    // Verification key
	VerifyKeyHash   string    `gorm:"column:verify_key_hash;not null;comment:Hashed verification key" json:"verify_key_hash"`                   // Hashed verification key
	VerifyType      int32     `gorm:"column:verify_type;default:1;comment:Type of verification" json:"verify_type"`                             // Type of verification
	IsVerified      int32     `gorm:"column:is_verified;comment:Verification status (0: Not Verified, 1: Verified)" json:"is_verified"`         // Verification status (0: Not Verified, 1: Verified)
	IsDeleted       int32     `gorm:"column:is_deleted;comment:Deleted status (0: Active, 1: Deleted)" json:"is_deleted"`                       // Deleted status (0: Active, 1: Deleted)
	VerifyCreatedAt time.Time `gorm:"column:verify_created_at;default:CURRENT_TIMESTAMP;comment:Record creation time" json:"verify_created_at"` // Record creation time
	VerifyUpdatedAt time.Time `gorm:"column:verify_updated_at;default:CURRENT_TIMESTAMP;comment:Record update time" json:"verify_updated_at"`   // Record update time
}

// TableName GoDbVerifyOtp's table name
func (*GoDbVerifyOtp) TableName() string {
	return TableNameGoDbVerifyOtp
}
